language: python
python:
  - "3.8"

services:
  - docker

before_script:
 - pip install docker-compose
 - pip install --upgrade pip setuptools
 - pip install flake8 flake8-docstrings restructuredtext-lint
 - "if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then pip install flake8-black; fi"
 - echo "Using restructuredtext-lint to check documentation"
 - echo "Using flake8 to check Python code"
 - flake8 setup.py flake8_rst_docstrings.py

script:
  - docker-compose run app sh -c "python manage.py test && flake8"
  - echo "Checking our own docstrings are valid RST"
  - flake8 --select RST setup.py flake8_rst_docstrings.py
